version: "3.7" # https://docs.docker.com/compose/compose-file/

networks:
  oc_test:
    external: true
  selenoid:
    external:
      name: oc_test


services:
  selenoid:
    networks:
      selenoid: null
    image: "aerokube/selenoid"
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/selenoid/video:/opt/selenoid/video"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "oc_test"]

  selenoid-ui:
    networks:
      selenoid: null
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8081:8081"
    depends_on:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

